<h3>Train a KNN model on glass type dataset and find best n_neighnours.</h3>

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [14]:
data=pd.read_csv("../Datas/knn_datasets/glass.csv")


In [18]:
data.sample(10)

RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  Type
41   1.51755  12.71  3.42  1.20  73.20  0.59   8.64  0.00  0.00     1
147  1.51610  13.33  3.53  1.34  72.67  0.56   8.33  0.00  0.00     3
29   1.51784  13.08  3.49  1.28  72.86  0.60   8.49  0.00  0.00     1
149  1.51643  12.16  3.52  1.35  72.89  0.57   8.53  0.00  0.00     3
209  1.51623  14.14  0.00  2.88  72.61  0.08   9.18  1.06  0.00     7
186  1.51838  14.32  3.26  2.22  71.25  1.46   5.79  1.63  0.00     7
84   1.51409  14.25  3.09  2.08  72.28  1.10   7.08  0.00  0.00     2
151  1.52127  14.32  3.90  0.83  71.50  0.00   9.49  0.00  0.00     3
16   1.51784  12.68  3.67  1.16  73.11  0.61   8.70  0.00  0.00     1
50   1.52320  13.72  3.72  0.51  71.75  0.09  10.06  0.00  0.16     1

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [28]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [26]:
x.shape

(214, 9)

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [30]:
x_train.shape

(160, 9)

In [31]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [33]:
X_train=scaler.fit_transform(x_train)
X_train

array([[ 0.22583258,  1.96434593, -1.48929762, ...,  0.79667748,
        -0.32839626, -0.5715004 ],
       [ 1.35368202,  0.38660832,  0.77897873, ...,  0.64192022,
        -0.32839626, -0.5715004 ],
       [-0.74790078, -0.11426076,  0.54918603, ..., -0.39716424,
        -0.32839626, -0.5715004 ],
       ...,
       [-0.10691802, -0.79043402,  0.52694802, ..., -0.07291094,
        -0.32839626, -0.5715004 ],
       [-0.70236648,  0.97512949, -2.06748571, ...,  0.12606269,
         0.59260991,  0.34087274],
       [ 1.7389722 ,  0.3740866 ,  0.69002672, ...,  0.87774081,
        -0.32839626,  1.05049629]])

In [35]:
X_test=scaler.transform(x_test)
X_test

array([[-3.20578943e-01,  1.91425902e+00, -2.06748571e+00,
         8.07429109e-01,  4.45765452e-01, -7.22391539e-01,
        -1.90821229e-01,  3.24050266e+00, -5.71500396e-01],
       [ 1.39571368e+00,  1.26312922e+00, -2.06748571e+00,
        -8.82692329e-01,  2.00390737e-02, -5.84924072e-01,
         1.95367224e+00, -3.28396264e-01,  2.39497949e-01],
       [ 3.33967776e+00, -9.78259926e-01, -2.06748571e+00,
        -1.57986742e+00, -8.44717632e-01, -6.39911059e-01,
         4.07605753e+00, -3.28396264e-01, -5.71500396e-01],
       [-3.38092132e-01,  1.60121585e+00, -2.06748571e+00,
         1.94826108e+00,  8.31579982e-01, -7.22391539e-01,
         5.97381450e-02,  1.19126392e+00, -5.71500396e-01],
       [-2.54028821e-01, -7.65390566e-01,  5.78836699e-01,
        -1.43264200e-01,  4.85677300e-01,  1.29906756e-01,
        -2.05560016e-01, -3.28396264e-01, -5.71500396e-01],
       [-6.13837309e-02, -5.27477752e-01,  7.49328059e-01,
        -7.13680185e-01,  5.52197046e-01,  4.742627

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
knn=KNeighborsClassifier(n_neighbors=3)

In [38]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [39]:
y_pred=knn.predict(x_test)

In [40]:
y_pred

array([6, 2, 2, 6, 6, 6, 2, 6, 6, 2, 2, 6, 6, 6, 6, 2, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 6, 6, 6, 6, 6, 2, 6,
       6, 6, 6, 6, 2, 6, 2, 6, 6, 6])

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.09259259259259259

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 0,  0,  0,  0, 19,  0],
       [ 0,  5,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  1,  0],
       [ 0,  4,  0,  0,  1,  0],
       [ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0]])