In [2]:
import numpy as np

In [ ]:
# syntific computing
# import numpy array
# mathmatical functions


In [4]:
# create Numpy
# np.array
a=np.array([1,2,3,4,5])
# a
a=np.array([1,2,3,4],dtype=float)
a

array([1., 2., 3., 4.])

In [6]:
# np.arange
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [8]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# np.ones and np.Zeros
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# np.randam
a=np.random.random((3,5))
a

array([[0.16758819, 0.80424384, 0.95380774, 0.19990518, 0.03702928],
       [0.17333797, 0.30718633, 0.67991621, 0.20894952, 0.83692588],
       [0.80643634, 0.70847494, 0.10305775, 0.13527987, 0.8644745 ]])

In [15]:
# np.lispace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
# np.idantity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# Atributes
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [19]:
# ndim
a3.ndim

3

In [20]:
a1.ndim

1

In [22]:
a2.ndim

2

In [23]:
# shape
a3.shape


(2, 2, 2)

In [24]:
# size
a3.size


8

In [28]:
# itemsize
print(a3.itemsize)
print(a3)
a2.itemsize

4
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


8

In [31]:
a1.dtype
a3.dtype
a2.dtype

dtype('float64')

CHANGIN DATATYPE

In [32]:
a3.dtype

dtype('int32')

In [38]:
a3.astype(np.float64)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [40]:
# scaler operations
print(a1)
a1+2

[0 1 2 3 4 5 6 7 8 9]


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a2>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
# vector operations
a2=a1
a1+a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
a1**a2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [44]:
# array Functions
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[ 5., 21., 16.],
       [44., 65., 45.],
       [64.,  9., 35.]])

In [47]:
np.sum(a1)
np.prod(a1)
np.max(a1,axis=0)


array([64., 65., 45.])

In [52]:
# mean,median,std,ver
np.mean(a1,axis=0)
np.median(a1)
np.std(a1)
np.var(a1)

449.06172839506166

In [53]:
# Trignometry functions
np.sin(a1)


array([[-0.95892427,  0.83665564, -0.28790332],
       [ 0.01770193,  0.82682868,  0.85090352],
       [ 0.92002604,  0.41211849, -0.42818267]])

In [54]:
# dot Product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)




array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [56]:
# log and exponents

np.exp(a1)
np.log(a1)

array([[1.60943791, 3.04452244, 2.77258872],
       [3.78418963, 4.17438727, 3.80666249],
       [4.15888308, 2.19722458, 3.55534806]])

In [59]:
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[94., 98., 79.],
       [23., 43., 69.]])

In [62]:
# Indexing and slising
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a1[-1]

9

In [65]:
print(a2)
a2[1,2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6

In [68]:
print(a3)
a3[1,0,1]
a3[0,1,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


2

In [69]:
a3[1,1,0]

6

In [72]:
# slising

a1
a1[2:5]
a1[2:5:2]

array([2, 4])

In [77]:
print(a2)
a2[0,:]
a2[:,2]
a2[1:,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  6],
       [ 9, 10]])

In [78]:
a2[::2,::3,]

array([[ 0,  3],
       [ 8, 11]])

In [79]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [81]:
a2[1,::3]

array([4, 7])

In [82]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [85]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
a3[0,1,:]

array([3, 4, 5])

In [88]:
a3[1,1]

array([12, 13, 14])

In [89]:
a3[1,:,1]

array([10, 13, 16])

In [90]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [93]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [96]:
# itrating
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [97]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [98]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [99]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [102]:
for i in np.nditer(a3):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [104]:
# reshape
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [105]:
# raval
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [110]:
# horizontal staking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [113]:
np.hstack((a4,a5,a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15,
         0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19,
         4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23,
         8,  9, 10, 11]])

In [114]:
# Vstack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [116]:
# splating
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [117]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]