In [2]:
import numpy as np

In [3]:
# sort
a=np.random.randint(1,100,15)
np.sort(a)

array([ 2,  4, 10, 15, 16, 23, 24, 33, 38, 43, 44, 48, 51, 52, 68])

In [4]:
a

array([44, 16, 33, 68, 15,  4, 48, 51, 23, 38, 24,  2, 52, 43, 10])

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[29, 72, 99, 47],
       [50, 33, 17, 99],
       [80, 73, 90, 45],
       [16, 18, 18, 59],
       [24,  1, 65, 42],
       [22, 24, 19, 97]])

In [6]:
np.sort(a)

array([ 2,  4, 10, 15, 16, 23, 24, 33, 38, 43, 44, 48, 51, 52, 68])

In [7]:
np.sort(a,axis=0)
np.sort(a,axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# np.append
np.append(a,200)

array([ 40,  82,  21,  20,  12,  16,  27,   5,  96,  67,  87,  20,  14,
        57,  78, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[66., 68., 61., 65.,  1.],
       [85., 42., 37., 97.,  1.],
       [65.,  4., 22., 23.,  1.],
       [82., 72., 19., 87.,  1.],
       [12., 19., 92., 83.,  1.],
       [ 9., 12., 62., 98.,  1.]])

In [ ]:
# np.concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
# np.uniq
a=np.array([1,2,2,2,3,5,3,4,4,5,1,1,1,7])


In [ ]:
# np.expend_dims
b=np.expand_dims(a,axis=1)
a

array([1, 2, 2, 2, 3, 5, 3, 4, 4, 5, 1, 1, 1, 7])

In [8]:
# np.where
np.where(a>2,0,a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])

In [ ]:
# np.argma
np.argmax(a)

13

In [ ]:
# np.armin
np.argmin(a)

0

In [9]:
a

array([44, 16, 33, 68, 15,  4, 48, 51, 23, 38, 24,  2, 52, 43, 10])

In [10]:
np.cumsum(a)

array([ 44,  60,  93, 161, 176, 180, 228, 279, 302, 340, 364, 366, 418,
       461, 471])

In [11]:
# np.cumproduct
np.cumproduct(a)

array([         44,         704,       23232,     1579776,    23696640,
          94786560,   254787584,   109264896, -1781874688,  1008238592,
       -1572077568,  1150812160,  -287309824,   530579456,  1010827264])

In [14]:
# np.percentile
np.percentile(a,100)
np.percentile(a,75)


46.0

In [16]:
# np.histogram
np.histogram(a,bins=[0,10,20,30,40,50,60,70])

(array([2, 3, 2, 2, 3, 2, 1], dtype=int64),
 array([ 0, 10, 20, 30, 40, 50, 60, 70]))

In [22]:
# np.corrrelate
np.corrcoef(a,a)

array([[1., 1.],
       [1., 1.]])

In [23]:
# np.isin
np.isin(a,[1,2,3,4,4,5,2,2323,2,23,])

array([False, False, False, False, False,  True, False, False,  True,
       False, False,  True, False, False, False])

In [25]:
a

array([44, 16, 33, 68, 15,  4, 48, 51, 23, 38, 24,  2, 52, 43, 10])

In [24]:
# flip
np.flip(a)

array([10, 43, 52,  2, 24, 38, 23, 51, 48,  4, 15, 68, 33, 16, 44])

In [26]:
# np.put
np.put(a,[0,1],[110,530])
a

array([110, 530,  33,  68,  15,   4,  48,  51,  23,  38,  24,   2,  52,
        43,  10])