In [7]:
import numpy as np

In [8]:
# sort
a=np.random.randint(1,100,15)
np.sort(a)

array([ 6, 21, 25, 34, 35, 41, 51, 53, 55, 64, 64, 70, 89, 93, 96])

In [9]:
a

array([96, 89, 64,  6, 25, 55, 51, 70, 34, 21, 64, 41, 53, 35, 93])

In [42]:
a=np.random.randint(1,100,24).reshape(6,4)
a


array([[14, 45, 48, 90],
       [90, 60,  8, 27],
       [31, 38, 69, 37],
       [14, 15, 49, 16],
       [66, 73, 82, 67],
       [41, 85, 70,  1]])

In [40]:
# np.sort(a)

array([[40, 50, 60, 78],
       [ 8, 19, 79, 95],
       [39, 41, 55, 86],
       [ 1, 13, 33, 78],
       [29, 48, 83, 96],
       [20, 24, 25, 77]])

In [44]:
np.sort(a,axis=0)
# np.sort(a,axis=1)


array([[14, 15,  8,  1],
       [14, 38, 48, 16],
       [31, 45, 49, 27],
       [41, 60, 69, 37],
       [66, 73, 70, 67],
       [90, 85, 82, 90]])

In [13]:
# np.append
np.append(a,200)

array([ 88,  46,  76,  69,  30,  86,  44,  38,   9,  36,  17,  58,  65,
        61,  87,  32,  13,  47,  53,   2,  27,  87,   8,  66, 200])

In [51]:
np.append(a,np.ones((a.shape[0],1)),axis=1)
np.append(a,np.ones((1,a.shape[1])),axis=0)

array([[14., 45., 48., 90.],
       [90., 60.,  8., 27.],
       [31., 38., 69., 37.],
       [14., 15., 49., 16.],
       [66., 73., 82., 67.],
       [41., 85., 70.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [52]:
# np.concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
np.concatenate
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [54]:
# np.uniq
a=np.array([1,2,2,2,3,5,3,4,4,5,1,1,1,7])
np.unique(a)


array([1, 2, 3, 4, 5, 7])

In [18]:
# np.expend_dims
b=np.expand_dims(a,axis=1)
a

array([1, 2, 2, 2, 3, 5, 3, 4, 4, 5, 1, 1, 1, 7])

In [19]:
# np.where
np.where(a>2,0,a)

array([1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [20]:
# np.argma
np.argmax(a)

13

In [21]:
# np.armin
np.argmin(a)

0

In [22]:
a

array([1, 2, 2, 2, 3, 5, 3, 4, 4, 5, 1, 1, 1, 7])

In [23]:
np.cumsum(a)

array([ 1,  3,  5,  7, 10, 15, 18, 22, 26, 31, 32, 33, 34, 41])

In [24]:
# np.cumproduct
np.cumproduct(a)

array([     1,      2,      4,      8,     24,    120,    360,   1440,
         5760,  28800,  28800,  28800,  28800, 201600])

In [25]:
# np.percentile
np.percentile(a,100)
np.percentile(a,75)


4.0

In [26]:
# np.histogram
np.histogram(a,bins=[0,10,20,30,40,50,60,70])

(array([14,  0,  0,  0,  0,  0,  0]), array([ 0, 10, 20, 30, 40, 50, 60, 70]))

In [27]:
# np.corrrelate
np.corrcoef(a,a)

array([[1., 1.],
       [1., 1.]])

In [55]:
# np.isin
np.isin(a,[1,2,3,4,4,5,2,2323,2,23])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False])

In [29]:
a

array([1, 2, 2, 2, 3, 5, 3, 4, 4, 5, 1, 1, 1, 7])

In [30]:
# flip
np.flip(a)

array([7, 1, 1, 1, 5, 4, 4, 3, 5, 3, 2, 2, 2, 1])

In [31]:
# np.put
np.put(a,[0,1],[110,530])
a

array([110, 530,   2,   2,   3,   5,   3,   4,   4,   5,   1,   1,   1,
         7])