In [3]:
# !pip install tensorflow tensorflow_hub pandas numpy scikit-learn


In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer

# Load the Universal Sentence Encoder model
# embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

/home/veer/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
2024-06-02 09:31:45.177934: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-02 09:31:45.180344: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-02 09:31:45.322157: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-02 09:31:45.819787: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable t

In [2]:
import tensorflow_hub as hub

# Load Universal Sentence Encoder model
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")


In [33]:
# Load and preprocess the dataset
data = pd.read_csv("ipc_data.csv")  # Assuming the dataset is saved in a CSV file




In [34]:
data=data[~data.Discription.isnull()]

In [35]:
X = embed(data['Discription'].values)

In [36]:
X

<tf.Tensor: shape=(312, 512), dtype=float32, numpy=
array([[-0.04351358,  0.01203886, -0.02172268, ..., -0.07356387,
         0.02624925, -0.00132717],
       [-0.03055553,  0.03949549, -0.02067022, ..., -0.05811677,
        -0.008237  , -0.01576594],
       [-0.01730238, -0.0284366 ,  0.03555203, ..., -0.04107082,
         0.01843588,  0.01834757],
       ...,
       [ 0.05138651,  0.05599338, -0.02501909, ..., -0.03916325,
        -0.01511848, -0.02185837],
       [ 0.03033582,  0.05499876, -0.03415346, ..., -0.01438594,
        -0.01788134, -0.01033866],
       [-0.02625556, -0.00265805, -0.03847776, ..., -0.04970175,
        -0.01467957, -0.02179479]], dtype=float32)>

In [37]:
data['Section']=data['Section'].apply(lambda x: [x] if isinstance(x, str) else [])


In [38]:
data.head()

Section                                            Offence  \
0  [IPC Section 109]  Abetment of any offence, if the act abetted is...   
1  [IPC Section 110]  Abetment of any offence, if the person abetted...   
2  [IPC Section 111]  Abetment of any offence, when one act is abett...   
3  [IPC Section 113]  Abetment of any offence, when an effect is cau...   
4  [IPC Section 114]  Abetment of any offence, if abettor is present...   

                                         Discription             Bail  \
0  Whoever abets any offence shall, if the act ab...  Same As Offence   
1  Whoever abets the commission of an offence sha...  Same As Offence   
2  When an Act is abetted and a different act is ...  Same As Offence   
3  When an act is abetted with the intention on t...  Same As Offence   
4  Whenever any person who if absent would be lia...  Same As Offence   

        Punishment       Triable_By       Congizance  
0  Same As Offence  Same As Offence  Same As Offence  
1  Same As Offence  Same As Offence  Same As Offence  
2  Same As Offence  Same As Offence  Same As Offence  
3  Same As Offence  Same As Offence  Same As Offence  
4  Same As Offence  Same As Offence  Same As Offence

In [39]:
# MultiLabelBinarizer to encode IPC sections
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(data['Section'])

In [43]:
y.shape

(312, 312)

In [44]:
X

<tf.Tensor: shape=(312, 512), dtype=float32, numpy=
array([[-0.04351358,  0.01203886, -0.02172268, ..., -0.07356387,
         0.02624925, -0.00132717],
       [-0.03055553,  0.03949549, -0.02067022, ..., -0.05811677,
        -0.008237  , -0.01576594],
       [-0.01730238, -0.0284366 ,  0.03555203, ..., -0.04107082,
         0.01843588,  0.01834757],
       ...,
       [ 0.05138651,  0.05599338, -0.02501909, ..., -0.03916325,
        -0.01511848, -0.02185837],
       [ 0.03033582,  0.05499876, -0.03415346, ..., -0.01438594,
        -0.01788134, -0.01033866],
       [-0.02625556, -0.00265805, -0.03847776, ..., -0.04970175,
        -0.01467957, -0.02179479]], dtype=float32)>

In [49]:
y=tf.reshape(y, [312, 1])

2024-06-02 09:46:34.049575: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Input to reshape is a tensor with 97344 values, but the requested shape has 312


InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 97344 values, but the requested shape has 312 [Op:Reshape]

In [46]:
X.shape

TensorShape([312, 512])

In [41]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got array([111, 208, 145, 203,  78, 245,  59, 248,   6, 183,  30,  22, 271,
        56, 301, 119, 258, 244, 204, 137, 168,  90, 224,  66, 118, 198,
       304,  19, 147,  92,  79, 101, 193,  72, 298,  15,  10, 167, 152,
        97,  68, 237,  37,  16,  55, 155, 281,  67, 113,  69,  31, 184,
       158, 238, 126,  18, 295,  96, 140, 176,  86, 262, 272, 154, 268,
       221, 218, 132, 194, 139, 195, 129,  38, 206, 181, 144, 112, 177,
       117, 288, 282, 163, 186, 307,   2, 115, 300, 234, 120, 223, 269,
       127,  74,  29,  83, 297, 107, 247, 294, 133, 255, 229,  65, 210,
        85, 226, 159,  12,  35,  28, 170, 142, 202, 131, 179,  51,  95,
       220, 178, 233,  41,  89, 230, 136,  26, 305, 141, 280,   0, 279,
       283, 100, 192, 267, 103, 171,  98,  36,  61, 150, 250, 246, 256,
        11, 308, 200, 278,  27, 232,   4, 122,  32, 290, 162, 222, 265,
       138,  62, 215, 135, 128, 302,   8,  70, 274,  64,  44, 249, 156,
        40, 123, 286, 216, 153,  23, 285, 110,  81, 236, 207, 212,  39,
       254, 303, 266, 199,  14,  47,  94, 275, 227, 284, 201, 161,  43,
       217, 190, 259, 105,  53,   1,  49,  80, 205,  34, 263,  91,  52,
       264, 241,  13,  88, 273, 166, 306, 134, 299, 243,  54,  50, 174,
       189, 310, 187, 169,  58,  48, 235, 252,  21, 160, 276, 191, 293,
       257, 149, 130, 151,  99,  87, 214, 121, 311,  20, 188,  71, 106,
       270, 102])

In [6]:
data.head()

Section                                            Offence  \
0  IPC Section 109  Abetment of any offence, if the act abetted is...   
1  IPC Section 110  Abetment of any offence, if the person abetted...   
2  IPC Section 111  Abetment of any offence, when one act is abett...   
3  IPC Section 113  Abetment of any offence, when an effect is cau...   
4  IPC Section 114  Abetment of any offence, if abettor is present...   

                                         Discription             Bail  \
0  Whoever abets any offence shall, if the act ab...  Same As Offence   
1  Whoever abets the commission of an offence sha...  Same As Offence   
2  When an Act is abetted and a different act is ...  Same As Offence   
3  When an act is abetted with the intention on t...  Same As Offence   
4  Whenever any person who if absent would be lia...  Same As Offence   

        Punishment       Triable_By       Congizance  
0  Same As Offence  Same As Offence  Same As Offence  
1  Same As Offence  Same As Offence  Same As Offence  
2  Same As Offence  Same As Offence  Same As Offence  
3  Same As Offence  Same As Offence  Same As Offence  
4  Same As Offence  Same As Offence  Same As Offence

In [23]:
data.Section.values[0:50]

array([list(['IPC Section 109']), list(['IPC Section 110']),
       list(['IPC Section 111']), list(['IPC Section 113']),
       list(['IPC Section 114']), list(['IPC Section 115']),
       list(['IPC Section 117']), list(['IPC Section 118']),
       list(['IPC Section 119']), list(['IPC Section 120']),
       list(['IPC Section 120B']), list(['IPC Section 121']),
       list(['IPC Section 122']), list(['IPC Section 123']),
       list(['IPC Section 124']), list(['IPC Section 124A']),
       list(['IPC Section 125']), list(['IPC Section 126']),
       list(['IPC Section 128']), list(['IPC Section 129']),
       list(['IPC Section 130']), list(['IPC Section 131']),
       list(['IPC Section 132']), list(['IPC Section 133']),
       list(['IPC Section 134']), list(['IPC Section 135']),
       list(['IPC Section 136']), list(['IPC Section 137']),
       list(['IPC Section 138']), list(['IPC Section 140']),
       list(['IPC Section 143']), list(['IPC Section 144']),
       list(['IPC Sect

In [7]:
data=data[~data.Discription.isnull()]

In [8]:
data['Discription'] = data['Discription'].fillna('').astype(str)
data['Section'] = data['Section'].apply(lambda x: [x] if isinstance(x, str) else [])


In [9]:
# Encode IPC Sections
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(data['Section'])



In [10]:
# Encode descriptions using Universal Sentence Encoder
X = np.array(embed(data['Discription'].values.tolist()))

2024-06-02 08:53:22.774499: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT64 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


In [11]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [12]:
# Build the model
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(y_train.shape[1], activation='sigmoid')
])

/home/veer/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:

model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])


In [14]:
# Train the model
history = model.fit(X_train, y_train, epochs=5, batch_size=16, validation_data=(X_test, y_test))


Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0000e+00 - loss: 0.6692 - val_accuracy: 0.0000e+00 - val_loss: 0.4526
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.3191 - val_accuracy: 0.0000e+00 - val_loss: 0.0278
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0019 - loss: 0.0410 - val_accuracy: 0.0000e+00 - val_loss: 0.0323
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.0330 - val_accuracy: 0.0000e+00 - val_loss: 0.0336
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.0311 - val_accuracy: 0.0000e+00 - val_loss: 0.0309


In [15]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.0311 
Test Accuracy: 0.00


In [53]:
# Predict IPC sections for new cases
def predict_ipc(case_description):
    encoded_case = np.array(embed([case_description]))
    prediction = model.predict(encoded_case)
    # Debugging: Print the raw prediction probabilities
    print(f"Raw prediction probabilities: {prediction}")
    predicted_ipcs = mlb.inverse_transform(prediction > 0.1)  # Use a lower threshold
    return predicted_ipcs


In [54]:
# Example usage
new_case = "The accused was found guilty of theft and resisting arrest."
predicted_ipcs = predict_ipc(new_case)
print(f"Predicted IPC Sections: {predicted_ipcs}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Raw prediction probabilities: [[0.04496825 0.04979632 0.03947706 0.01686654 0.04859875 0.01152784
  0.04575975 0.01494631 0.04918941 0.01774681 0.03914184 0.03900272
  0.04065891 0.04762815 0.04912697 0.04683689 0.04596532 0.01575687
  0.04797711 0.05312864 0.03658072 0.04282473 0.04067949 0.04062546
  0.01808222 0.01349422 0.04464406 0.04324792 0.05415929 0.04201289
  0.04096145 0.04690265 0.04298601 0.01200131 0.05249808 0.03934827
  0.04559562 0.04771182 0.04309622 0.04858919 0.04624978 0.04257119
  0.01471197 0.04324523 0.03641069 0.01410774 0.0121232  0.05972177
  0.04748665 0.05790872 0.05272335 0.0615026  0.04711714 0.04997263
  0.04375865 0.0409556  0.04381282 0.01486461 0.0537054  0.03905688
  0.0154223  0.037258   0.03583967 0.0187433  0.04065423 0.04501718
  0.04304081 0.03852106 0.03543204 0.04393522 0.04713131 0.04510562
  0.04885085 0.015231   0.0481772  0.01321889 0.01640171 0.01107754
  0.04542899 0.05123484 0.04812858 0.03897619 0.

In [15]:
data['Section'] = data['Section'].apply(lambda x: x.split(','))

In [29]:
data.head()

Section                                            Offence  \
0  [IPC Section 109]  Abetment of any offence, if the act abetted is...   
1  [IPC Section 110]  Abetment of any offence, if the person abetted...   
2  [IPC Section 111]  Abetment of any offence, when one act is abett...   
3  [IPC Section 113]  Abetment of any offence, when an effect is cau...   
4  [IPC Section 114]  Abetment of any offence, if abettor is present...   

                                         Discription             Bail  \
0  Whoever abets any offence shall, if the act ab...  Same As Offence   
1  Whoever abets the commission of an offence sha...  Same As Offence   
2  When an Act is abetted and a different act is ...  Same As Offence   
3  When an act is abetted with the intention on t...  Same As Offence   
4  Whenever any person who if absent would be lia...  Same As Offence   

        Punishment       Triable_By       Congizance  
0  Same As Offence  Same As Offence  Same As Offence  
1  Same As Offence  Same As Offence  Same As Offence  
2  Same As Offence  Same As Offence  Same As Offence  
3  Same As Offence  Same As Offence  Same As Offence  
4  Same As Offence  Same As Offence  Same As Offence

In [30]:
# Encode Section
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(data['Section'])



In [33]:
X = np.array(embed(data['Discription'].values.tolist()))

In [34]:
# Encode Discriptions using Universal Sentence Encoder
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [35]:
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(y_train.shape[1], activation='sigmoid')
])



/home/veer/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])


In [37]:
# Train the model
history = model.fit(X_train, y_train, epochs=25, batch_size=32, validation_data=(X_test, y_test))



Epoch 1/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.0000e+00 - loss: 0.6859 - val_accuracy: 0.0000e+00 - val_loss: 0.6385
Epoch 2/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.5998 - val_accuracy: 0.0159 - val_loss: 0.4056
Epoch 3/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.3425 - val_accuracy: 0.0159 - val_loss: 0.0893
Epoch 4/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0023 - loss: 0.0858 - val_accuracy: 0.0159 - val_loss: 0.0247
Epoch 5/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0014 - loss: 0.0368 - val_accuracy: 0.0159 - val_loss: 0.0300
Epoch 6/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0035 - loss: 0.0338 - val_accuracy: 0.0159 - val_loss: 0.0345
Epoch 7/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.0355 - val_accuracy: 0.0000e+00 - val_loss: 0.0355
Epoch 8/25
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0027 - loss: 0.0341 - val_accuracy: 0.0000e+0

In [38]:
# Evaluate the model
oss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.0289 
Test Accuracy: 0.00


In [39]:
# Predict IPC sections for new cases
def predict_ipc(Discription):
    encoded_case = np.array(embed([Discription]))
    prediction = model.predict(encoded_case)
    predicted_ipcs = mlb.inverse_transform(prediction > 0.5)
    return predicted_ipcs




In [40]:
# Example usage
new_case = "The accused was found guilty of theft and resisting arrest."
predicted_ipcs = predict_ipc(new_case)
print(f"Predicted IPC Sections: {predicted_ipcs}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Predicted IPC Sections: [()]
